### ISSUE TITLE
Play all from search results has stopped working

### ISSUE THREAD

**Issue by sprnza** [cristianpb/muse#12]
Hi!
I'm not sure if it's Muse- related issue, but now if I click "play all" from search results I've got an error in Mopiy log (truncated)
```
2020-07-24 12:26:20,402 INFO [1988:Core-10] pykka: Exception returned from Core (urn:uuid:94d059fd-f1b7-4dfb-8670-6fe47e8d22bb) to caller:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3.8/site-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3.8/site-packages/mopidy/core/tracklist.py", line 383, in add
    uris is None or validation.check_uris(uris)
  File "/usr/lib/python3.8/site-packages/mopidy/internal/validation.py", line 133, in check_uris
    [check_uri(a, msg) for a in arg]
  File "/usr/lib/python3.8/site-packages/mopidy/internal/validation.py", line 133, in <listcomp>
    [check_uri(a, msg) for a in arg]
  File "/usr/lib/python3.8/site-packages/mopidy/internal/validation.py", line 126, in check_uri
    raise exceptions.ValidationError(msg.format(arg=arg))
mopidy.exceptions.ValidationError: Expected a list of URIs, not [Track(album=Album(artists=[Artist(name=.........
```

**Comment by cristianpb** [comment]
Hi
Thanks for the review. Normally "Play All" should work for search results 🤔.

I will double check this and the other issues after holidays.

**Comment by cristianpb** [comment]
Hi,
I'm not able to reproduce the error. which "source" are you using for search ?
When I use "local" source it works fine.

**Comment by sprnza** [comment]
Hi!
Yep, it seems like it was a configuration issue. I'm not able to reproduce the error on my home server also. 
Sorry for bothering.
